alloy:
  podSecurityContext:
    supplementalGroups:
      - 0
    runAsNonRoot: true

  alloy:
    securityContext:
      runAsUser: 473
      runAsGroup: 473
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL

  configReloader:
    securityContext:
      runAsUser: 65534
      runAsGroup: 65534
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL

  mounts:
    varlog: true
    dockercontainers: true

